require_relative "./fireside_finder/version"
require_relative "./fireside_finder/cli"
require_relative './fireside_finder/gathering'
require_relative "./fireside_finder/scraper"
require_relative "./fireside_finder/geocoder"
require 'nokogiri'
require 'pry'
require 'geocoder'
require 'httparty'
